### ISSUE TITLE
On the citation of this dataset

### ISSUE THREAD

**Issue by nicolaus625** [GiantSteps/giantsteps-mtg-key-dataset#1]
What is the difference between [Giantsteps-key](https://github.com/GiantSteps/giantsteps-key-dataset
) and [Giantsteps-MTG-key](https://github.com/GiantSteps/giantsteps-mtg-key-dataset) dataset? What is the citation of this repo?

**Comment by richard-vogl** [comment]
Giantsteps-key [paper](http://www.cp.jku.at/research/papers/knees_etal_ismir_2015.pdf)
how to cite is noted in the [readme file]( https://github.com/GiantSteps/giantsteps-key-dataset/blob/master/README)

the giantsteps-mtg-key repo is an extension: more files, maybe a bit less trustworthy. 
there are some annotations that are problematic (modes instead of maj/min keys), but you have additionally confidence values (C) in the [annotations file](https://github.com/GiantSteps/giantsteps-mtg-key-dataset/blob/master/annotations/annotations.txt).
